### ISSUE TITLE
one hotkey for on/off

### ISSUE THREAD

**Issue by minimumcringetv** [upgradeQ/obs-filter-hotkeys#1]
Thanks for making this script!
I find it very useful and I saw people looking for a function like this for years. I find it weird that the program doesn't include this option already.
When controlling sources with hotkeys it is possible to enable and disable them with a single hotkey. However, the script you provided requires two separate hotkeys to turn filters on and off.
Is there a way to combine both under one hotkey? That would leave more keys for combinations and also require less memorization on the user side. I hope it's not a hard thing to code in.
Great job and looking forward for more useful OBS Studio stuff!

**Comment by upgradeQ** [comment]
It should be possible to toggle filter enabled state, using [API](https://obsproject.com/docs/reference-sources.html?highlight=enabled#c.obs_source_enabled) or via boolean switches / coroutines.

**Comment by upgradeQ** [comment]
Done here https://github.com/upgradeQ/obs-filter-hotkeys/blob/71d495a329c0c8ab5ff69f58e3919cfa432fd3c3/filter_hotkeys_audio.lua#L45-L47

**Comment by minimumcringetv** [comment]
thanks, I'll give it a try in a few hours!
