### ISSUE TITLE
Failed on OBS26.1

### ISSUE THREAD

**Issue by iesv** [upgradeQ/obs-filter-hotkeys#2]
![image](https://user-images.githubusercontent.com/16969250/103352615-a0c08280-4ae1-11eb-8f74-169d4fb70389.png)

**Comment by upgradeQ** [comment]
@iesvme hello, can you provide more details please?
- What source being filtered by `Filter hotkeys video`?
- What text comes after "Failed to call timer_cb for timer_cal: e:/Users/An..." ?
- Does this happen on OBS loading, or after you have added script via `Scripts` menu ?

**Comment by iesv** [comment]
![image](https://user-images.githubusercontent.com/16969250/103404482-b2ac2f00-4b8e-11eb-9553-b6e53ed8c4a8.png)

**Comment by iesv** [comment]
And also it cannot save the hotkey after restarting the OBS.

by the way, my OBS language is Chinese. The scene name is Chinese, too.

**Comment by upgradeQ** [comment]
I've tested with Chinese names and it works, both on scene and scene item. There is might be a problem when updating to new version also. In a folder with this script, rename it to something like `filter_hotkeys_video1.lua` that will trigger an error on load , it will prevent error messages to spam Script log. Then remove all `Filter hotkeys audio/video` filters from sources. Rename it back to `filter_hotkeys_video.lua` and try again. If error persist please send screenshots/video of that problem.

**Comment by upgradeQ** [comment]
@iesvme  I've changed registering hotkey method, now it's under `video_render`. Can you test [1.0.0 version](https://github.com/upgradeQ/obs-filter-hotkeys/releases/tag/1.0.0) ?

**Comment by iesv** [comment]
sure thing. thank you so much.

upgradeQ <notifications@github.com> 于 2021年1月24日周日 08:11写道：
