### ISSUE TITLE
VLC becomes black screen when I enable the filter hotkey thru audio.

### ISSUE THREAD

**Issue by iesv** [upgradeQ/obs-filter-hotkeys#3]
![image](https://user-images.githubusercontent.com/16969250/103452290-a0560080-4d08-11eb-951b-bc18b41d0d85.png)

**Comment by upgradeQ** [comment]
You can set visibility eye icon to not showing, this will let video feed to go through. Same thing in new version: https://github.com/upgradeQ/obs-filter-hotkeys/blob/6bffa49560c6fe29c205b7312f8d3a822b749a6f/filter_hotkeys_audio.lua#L64-L66
if filter id is filter hotkeys audio, then it will be added in disabled state.
