### ISSUE TITLE
Obs Filter Hotkey

### ISSUE THREAD

**Issue by ranytian** [upgradeQ/obs-filter-hotkeys#4]
Setup encounter error please help thanks:
[filter_hotkeys_audio.lua] Error loading file: E:/@DAW/OBS/filter_hotkeys_audio.lua:7: unexpected symbol near '<'

**Comment by upgradeQ** [comment]
@ranytian Hi, could you upload a log file please ? 
1. Press WinKey+R to open the Run dialog
2. Paste the following into the box and hit OK: %APPDATA%\obs-studio\logs
3. Find the desired log file (usually the latest) and drag/drop it to upload it.
4. If possible screen record the error and paste it here.
 Also current latest release is 1.0.1 download link -  https://github.com/upgradeQ/obs-filter-hotkeys/releases/tag/1.0.1

**Comment by upgradeQ** [comment]
@ranytian I guess it's your account on forums https://obsproject.com/forum/threads/obs-filter-hotkeys.132411/post-508404
