### ISSUE TITLE
obs-dock-hotkeys

### ISSUE THREAD

**Issue by iesv** [upgradeQ/obs-filter-hotkeys#5]
Hello, sir.
Can you develop the "obs-dock-hotkeys"?
It will show or hide dock.
Thank you in advance.

**Comment by upgradeQ** [comment]
There is no way to access C++ API within a Lua script, even with LuaJIT.
[This](https://github.com/obsproject/obs-studio/blob/190ab876cc727a1d9ef89a32f065fa25efc17f98/UI/window-basic-main.cpp#L187) is where toggle of docks happens, it's a Qt action you can't replicate that when no bindings provided.
However one might try using setting config variables to docks state, not sure if its updates in real time.Also using [`obs-libre-macros`](https://github.com/upgradeQ/obs-libre-macros) might streamline the process.
Consider posting this request here https://ideas.obsproject.com/ and here https://obsproject.com/forum/list/resource-requests.29/

**Comment by iesv** [comment]
now I get it. Thank you very much!

upgradeQ <notifications@github.com> 于 2021年2月27日周六 21:44写道：
