### ISSUE TITLE
Unable to toggle with same key binding

### ISSUE THREAD

**Issue by wildfunctions** [upgradeQ/obs-filter-hotkeys#6]
I have a filter on my mic audio, and I am able to bind keys to enable/disable. However, when using the same key for both, the filter will enable but no longer toggle afterwards.

I also noticed that I have 3 hotkey options. 0;Mic/Aux;MyFilter, 1;Mic/Aux;MyFilter, and 2;Mic/Aux;MyFilter. My understanding is that 0 is off, and 1 is on. Not sure what 2 is, so perhaps that is the issue?

Thanks.

**Comment by upgradeQ** [comment]
Make sure you are running latest version where you have 4 hotkey options.
https://github.com/upgradeQ/obs-filter-hotkeys/blob/0fd72031a95610a928fd7c7f020f138e0d1415bd/filter_hotkeys_audio.lua#L8-L12
enable/disable do not share that behavior, you will notice that it's not highlighted in red.

**Comment by wildfunctions** [comment]
Perfect! Working now!!! Thanks
