### ISSUE TITLE
Filters not showing up in hotkeys search

### ISSUE THREAD

**Issue by Joshy4890** [upgradeQ/obs-filter-hotkeys#7]
I loaded the script in OBS and it did nothing. I have no idea what could be wrong with it. I have a filter named "Noise Suppression" and it's not showing up like all the other filters. Made sure the search was case-sensitive too.

**Comment by upgradeQ** [comment]
@Joshy4890 did you follow all steps correctly & in order? You must add filters first, *then* add filter hotkeys filter. 
If that did not help, show the last log.

**Comment by Joshy4890** [comment]
> @Joshy4890 did you follow all steps correctly & in order? You must add filters first, _then_ add filter hotkeys filter.
> If that did not help, show the last log.
sorry, I figured out that I didn't add the hotkeys filter but it works now! Thanks for responding so fast anyway tho.
